config/routes.rb
Rails.application.routes.draw do
  resources :specialities

end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController
  before_action :set_speciality, only: [:show, :edit, :update, :destroy]

  # GET /specialities
  # GET /specialities.json
  def index
    @specialities = Speciality.all
  end

  # GET /specialities/1
  # GET /specialities/1.json
  def show
  end

  # GET /specialities/new
  def new
    @speciality = Speciality.new
  end

  # GET /specialities/1/edit
  def edit
  end

  # POST /specialities
  # POST /specialities.json
  def create
    @speciality = Speciality.new(speciality_params)

    respond_to do |format|
      if @speciality.save
        format.html { redirect_to @speciality, notice: 'Speciality was successfully created.' }
        format.json { render :show, status: :created, location: @speciality }
      else
        format.html { render :new }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialities/1
  # PATCH/PUT /specialities/1.json
  def update
    respond_to do |format|
      if @speciality.update(speciality_params)
        format.html { redirect_to @speciality, notice: 'Speciality was successfully updated.' }
        format.json { render :show, status: :ok, location: @speciality }
      else
        format.html { render :edit }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialities/1
  # DELETE /specialities/1.json
  def destroy
    @speciality.destroy
    respond_to do |format|
      format.html { redirect_to specialities_url, notice: 'Speciality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speciality
      @speciality = Speciality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speciality_params
      params.require(:speciality).permit(:name, :description, :seo_title, :seo_description, :seo_keywords, :speciality_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  <%= metamagic :title => "Medic App", :description => "None", :keywords => "None" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/specialities/_form.html.erb
<%= form_for(@speciality) do |f| %>
  <% if @speciality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speciality.errors.count, "error") %> prohibited this speciality from being saved:</h2>

      <ul>
      <% @speciality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :seo_title %><br>
    <%= f.text_field :seo_title %>
  </div>
  <div class="field">
    <%= f.label :seo_description %><br>
    <%= f.text_field :seo_description %>
  </div>
  <div class="field">
    <%= f.label :seo_keywords %><br>
    <%= f.text_field :seo_keywords %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specialities/edit.html.erb
<h1>Editing Speciality</h1>

<%= render 'form' %>

<%= link_to 'Show', @speciality %> |
<%= link_to 'Back', specialities_path %>

app/views/specialities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Specialities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Seo title</th>
      <th>Seo description</th>
      <th>Seo keywords</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialities.each do |speciality| %>
      <tr>
        <td><%= speciality.name %></td>
        <td><%= speciality.description %></td>
        <td><%= speciality.seo_title %></td>
        <td><%= speciality.seo_description %></td>
        <td><%= speciality.seo_keywords %></td>
        <td><%= link_to 'Show', speciality %></td>
        <td><%= link_to 'Edit', edit_speciality_path(speciality) %></td>
        <td><%= link_to 'Destroy', speciality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speciality', new_speciality_path %>

app/views/specialities/new.html.erb
<h1>New Speciality</h1>

<%= render 'form' %>

<%= link_to 'Back', specialities_path %>

app/views/specialities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @speciality.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @speciality.description %>
</p>

<p>
  <strong>Seo title:</strong>
  <%= @speciality.seo_title %>
</p>

<p>
  <strong>Seo description:</strong>
  <%= @speciality.seo_description %>
</p>

<p>
  <strong>Seo keywords:</strong>
  <%= @speciality.seo_keywords %>
</p>

<%= link_to 'Edit', edit_speciality_path(@speciality) %> |
<%= link_to 'Back', specialities_path %>